config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :posts

  resources :posts do
    post :add_comment 
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :text, length: {maximum: 15}
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :Comments	
	validates :text, length: {maximum: 15}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
http_basic_authenticate_with :name =>"razan", :password => "himalayantimes1"
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params['id'])
  end

  # GET /posts/new
  def new
    @post = Post.new
   ## binding.pry
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to PostsController_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_comment
     post = Post.find(params['post_id'])
     post.comments = "test"

     post.save
     redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titles, :text)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My App</title>
  
    <link rel="stylesheet" href="main.css" >
  

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>



</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <h3>Title
    <%= f.text_field :titles %></h3>
    <br>
   
    <h3>Text
      <%= f.text_area :text %></h3>
    <%= f.submit %>
  
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "main.css" %>

<div class="heading">
  
  <a target = "_blank" href="http://cloudfactory.com.np/">
    <img src="http://yourstory.com//wp-content/uploads/2012/10/cf-combined-logo-300x264.png">
  </a><img src="http://www.cloudfactory.com/hs-fs/hub/351374/file-461130609-jpg/img/cf-avaya.jpg">
  <h1 style="color:Black">Listing posts</h1>
</div>
<div class="jumbotron" style="color:White">
</div>/edit

<div class="body" style="color:White">

<table border = "1px">
  <thead>
    <tr>
      <th>Titles</th>
      <th>Text</th>
      <th colspan="5"></th>
      
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titles %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Erase', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>

</table>
</div>


<%= link_to 'Add New Post', new_post_path%>
<br>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
a
<%= @post.titles%>
<%= link_to 'AddComment', post_add_comment_path(@post.id), method: :post %>
<br>
<br>
<%=@post.comments%>